services:
  - type: web
    name: cpu-scheduler-backend
    env: python
    buildCommand: ./cpp_engine/build_cpp.sh && pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: ALLOWED_HOSTS
        value: '*'
