# Compiler and flags
CXX = g++
CXXFLAGS = -std=c++11 -Wall

# Source files
SRCS = main.cpp fcfs.cpp sjf.cpp priority.cpp rr.cpp srtf.cpp ljf.cpp hrrn.cpp lrtf.cpp

# Output binary name
OUT = scheduler_exec

# Build rule
all:
	$(CXX) $(CXXFLAGS) $(SRCS) -o $(OUT)

# Clean rule to delete compiled output
clean:
	rm -f $(OUT)
